package com.roy.mapper;

import com.roy.model.Chat;
import com.roy.model.ChatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    long countByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    int deleteByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    int insert(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    int insertSelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    List<Chat> selectByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    Chat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Chat record, @Param("example") ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Chat record, @Param("example") ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Chat record);

    //查询今天的聊天记录
    List<Chat> selectTodayMsg(Long tcId);
    //查询最近三天聊天记录
    List<Chat> selectRecentThreeDaysMsg(Long tcId);
    //查询最近一周聊天记录
    List<Chat> selectRecentWeekMsg(Long tcId);
    //查询最近两周聊天记录
    List<Chat> selectRecentTwoWeeksMsg(Long tcId);
    //查询本月聊天记录
    List<Chat> selectCurrentMouthMsg(Long tcId);
    //查询近三个月聊天记录
    List<Chat> selectRecentThreeMouthsMsg(Long tcId);
    //查询今年聊天记录
    List<Chat> selectCurrentYearMsg(Long tcId);
}